import { HelpCircle, Code, Zap, Package, ChevronRight } from "lucide-react";

export default function CampaignRules() {
    return (
        <div className="glass-panel rounded-3xl p-8 border-primary/20 primary-glow relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 blur-3xl -mr-16 -mt-16 animate-pulse" />

            <h3 className="text-xl font-black mb-8 flex items-center gap-3">
                <HelpCircle className="h-6 w-6 text-primary" />
                Campaign Guidelines
            </h3>

            <div className="space-y-8">
                <div className="relative pl-10 group">
                    <div className="absolute left-0 top-0 h-full w-px bg-border group-hover:bg-primary transition-colors duration-500"></div>
                    <div className="absolute left-[-4px] top-1.5 h-2 w-2 rounded-full bg-primary shadow-[0_0_15px_rgba(79,70,229,0.8)] animate-pulse" />
                    <h4 className="font-black text-[10px] uppercase tracking-[0.2em] text-primary mb-2 flex items-center gap-2">
                        <Code className="h-3.5 w-3.5" />
                        Development Activity
                    </h4>
                    <p className="text-sm text-muted-foreground leading-relaxed font-medium">
                        Rankings are heavily weighted by the frequency and quality of code contributions. High-impact GitHub activity directly boosts your percentile.
                    </p>
                </div>

                <div className="relative pl-10 group">
                    <div className="absolute left-0 top-0 h-full w-px bg-border group-hover:bg-primary transition-colors duration-500"></div>
                    <div className="absolute left-[-4px] top-1.5 h-2 w-2 rounded-full bg-primary/40 group-hover:bg-primary group-hover:shadow-[0_0_15px_rgba(79,70,229,0.5)] transition-all" />
                    <h4 className="font-black text-[10px] uppercase tracking-[0.2em] text-accent mb-2 flex items-center gap-2">
                        <Zap className="h-3.5 w-3.5" />
                        On-Chain Impact
                    </h4>
                    <p className="text-sm text-muted-foreground leading-relaxed font-medium">
                        Transactions and fees generated by your project on Stacks Mainnet contribute significantly to your final standing.
                    </p>
                </div>

                <div className="relative pl-10 group">
                    <div className="absolute left-0 top-0 h-full w-px bg-border group-hover:bg-primary transition-colors duration-500"></div>
                    <div className="absolute left-[-4px] top-1.5 h-2 w-2 rounded-full bg-primary/40 group-hover:bg-primary group-hover:shadow-[0_0_15px_rgba(79,70,229,0.5)] transition-all" />
                    <h4 className="font-black text-[10px] uppercase tracking-[0.2em] text-purple-400 mb-2 flex items-center gap-2">
                        <Package className="h-3.5 w-3.5" />
                        Package Distribution
                    </h4>
                    <p className="text-sm text-muted-foreground leading-relaxed font-medium">
                        Downloads of project-related npm packages (SDKs, libraries) act as a force multiplier for ecosystem adoption scores.
                    </p>
                </div>
            </div>

            <div className="mt-8 pt-6 border-t border-border">
                <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground italic">March 1st - March 31st</span>
                    <a href="#" className="flex items-center gap-1 text-primary font-bold hover:underline">
                        View Official FAQ
                        <ChevronRight className="h-4 w-4" />
                    </a>
                </div>
            </div>
        </div>
    );
}
