import { HelpCircle, CheckCircle2, ChevronRight } from "lucide-react";

export default function CampaignRules() {
    return (
        <div className="glass-panel rounded-xl p-6">
            <h3 className="text-lg font-bold mb-6 flex items-center gap-2">
                <HelpCircle className="h-5 w-5 text-primary" />
                Campaign Guidelines
            </h3>

            <div className="space-y-6">
                <div className="relative pl-8 group">
                    <div className="absolute left-0 top-0 h-full w-px bg-border group-hover:bg-primary transition-colors duration-500"></div>
                    <div className="absolute left-[-4px] top-1.5 h-2 w-2 rounded-full bg-primary shadow-[0_0_15px_rgba(79,70,229,0.6)] animate-pulse" />
                    <h4 className="font-bold text-foreground mb-1 flex items-center gap-2">
                        <CheckCircle2 className="h-3.5 w-3.5 text-primary" />
                        Development Activity
                    </h4>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                        Rankings are heavily weighted by the frequency and quality of code contributions. High-impact GitHub activity directly boosts your percentile.
                    </p>
                </div>

                <div className="relative pl-8 group">
                    <div className="absolute left-0 top-0 h-full w-px bg-border group-hover:bg-primary transition-colors duration-500"></div>
                    <div className="absolute left-[-4px] top-1 h-2 w-2 rounded-full bg-primary/40 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(var(--primary-rgb),0.5)] transition-all"></div>
                    <h4 className="font-bold text-foreground mb-1 flex items-center gap-2">
                        <CheckCircle2 className="h-3.5 w-3.5 text-primary/60 group-hover:text-primary transition-colors" />
                        On-Chain Impact
                    </h4>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                        Transactions and fees generated by your project on Stacks Mainnet contribute significantly to your final standing.
                    </p>
                </div>

                <div className="relative pl-8 group">
                    <div className="absolute left-0 top-0 h-full w-px bg-border group-hover:bg-primary transition-colors duration-500"></div>
                    <div className="absolute left-[-4px] top-1 h-2 w-2 rounded-full bg-primary/40 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(var(--primary-rgb),0.5)] transition-all"></div>
                    <h4 className="font-bold text-foreground mb-1 flex items-center gap-2">
                        <CheckCircle2 className="h-3.5 w-3.5 text-primary/60 group-hover:text-primary transition-colors" />
                        Package Distribution
                    </h4>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                        Downloads of project-related npm packages (SDKs, libraries) act as a force multiplier for ecosystem adoption scores.
                    </p>
                </div>
            </div>

            <div className="mt-8 pt-6 border-t border-border">
                <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground italic">March 1st - March 31st</span>
                    <a href="#" className="flex items-center gap-1 text-primary font-bold hover:underline">
                        View Official FAQ
                        <ChevronRight className="h-4 w-4" />
                    </a>
                </div>
            </div>
        </div>
    );
}
